import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import AgriProvider from "./_components/AgriProvider";
import React from "react";
import { AdvisoryDetailProvider as AgriDetailProvider } from "@/context/AdvisoryDetailContext";



const outfit=Outfit({subsets:['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    
      <html lang="en">
        <body>
           <AgriDetailProvider>
          {children}
        </AgriDetailProvider>
          </body>
      </html>
    
    </ClerkProvider>
  );
}
